services:
  - type: web
    name: house-price-fastapi
    runtime: python
    plan: free
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn src.app:app --host 0.0.0.0 --port $PORT
    autoDeploy: true
